pekko {
  loglevel = debug
  log-dead-letters = off
  log-dead-letters-during-shutdown = on

  remote.artery {
    transport = tcp
    canonical.hostname = "127.0.0.1"
  }

  cluster {
    seed-nodes = [
      "pekko://ClusterSystem@127.0.0.1:7354",
      "pekko://ClusterSystem@127.0.0.1:7355",
      "pekko://ClusterSystem@127.0.0.1:7356"
    ]
    downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"
    jmx.multi-mbeans-in-same-jvm = on
    sharding {
      passivation {
        default-idle-strategy {
          idle-entity.timeout = 2 minutes
        }
      }
    }
  }

  actor {
    provider = cluster
    serialization-bindings {
      "pcd.distributedSmartHomeAlarmSystem.CborSerializable" = jackson-cbor
    }
  }
}
