package pcd.client;

import pcd.util.LockTarget;
import java.util.concurrent.Callable;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/**
 * Utility class that provides an Execute Around pattern for distributed locks.
 * <p>
 * This class abstracts the lock acquisition and release lifecycle, guaranteeing
 * that locks are always released even if the critical section throws an exception.
 * It prevents lock leaks and separates synchronization logic from business logic.
 */
public final class LockExecutor {

    private static final ExecutorService VIRTUAL_EXECUTOR = Executors.newVirtualThreadPerTaskExecutor();

    private LockExecutor() {}

    /**
     * Executes a critical section synchronously while holding the specified distributed lock.
     * <p>
     * The calling thread blocks until the lock is acquired. The lock is automatically
     * released upon completion or failure of the critical section.
     *
     * @param lockManager     the manager responsible for acquiring and releasing the lock
     * @param target          the hierarchical lock identifier
     * @param criticalSection the business logic to execute within the lock
     * @param <T>             the return type of the critical section
     * @return the result generated by the critical section
     * @throws Exception if lock acquisition fails or the critical section throws an exception
     */
    public static <T> T executeInLock(DistributedLockManager lockManager, LockTarget target, Callable<T> criticalSection) throws Exception {
        lockManager.acquire(target);
        try {
            return criticalSection.call();
        } finally {
            lockManager.release(target);
        }
    }

    /**
     * Executes a critical section asynchronously while holding the specified distributed lock.
     * <p>
     * This method does not block the calling thread. It delegates the lock acquisition,
     * execution, and release lifecycle to a dedicated virtual thread.
     *
     * @param lockManager     the manager responsible for acquiring and releasing the lock
     * @param target          the hierarchical lock identifier
     * @param criticalSection the business logic to execute within the lock
     * @param <T>             the return type of the critical section
     * @return a {@code CompletableFuture} representing the pending result of the critical section
     */
    public static <T> CompletableFuture<T> executeInLockAsync(DistributedLockManager lockManager, LockTarget target, Callable<T> criticalSection) {
        return CompletableFuture.supplyAsync(() -> {
            try {
                return executeInLock(lockManager, target, criticalSection);
            } catch (Exception e) {
                if (e instanceof RuntimeException) {
                    throw (RuntimeException) e;
                }
                throw new RuntimeException("Error during critical section execution", e);
            }
        }, VIRTUAL_EXECUTOR);
    }
}